// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83uDegRrjOfUOSELvTkURRvcQNjgNJ9Y',
    appId: '1:388120889700:web:a74fce4675184e6c42d271',
    messagingSenderId: '388120889700',
    projectId: 'starsimapp',
    authDomain: 'starsimapp.firebaseapp.com',
    storageBucket: 'starsimapp.firebasestorage.app',
    measurementId: 'G-58N385H8C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9p8eW0QR0nN4D0T6GkT0p1QLMYI7QqyU',
    appId: '1:388120889700:android:321d9cb79c7aa28c42d271',
    messagingSenderId: '388120889700',
    projectId: 'starsimapp',
    storageBucket: 'starsimapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VTGRHBt2LfwVDV6WdGgUXuxsHabujFU',
    appId: '1:388120889700:ios:bb00f405727102f442d271',
    messagingSenderId: '388120889700',
    projectId: 'starsimapp',
    storageBucket: 'starsimapp.firebasestorage.app',
    iosBundleId: 'com.example.starsimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VTGRHBt2LfwVDV6WdGgUXuxsHabujFU',
    appId: '1:388120889700:ios:bb00f405727102f442d271',
    messagingSenderId: '388120889700',
    projectId: 'starsimapp',
    storageBucket: 'starsimapp.firebasestorage.app',
    iosBundleId: 'com.example.starsimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA83uDegRrjOfUOSELvTkURRvcQNjgNJ9Y',
    appId: '1:388120889700:web:1444db052b458cb642d271',
    messagingSenderId: '388120889700',
    projectId: 'starsimapp',
    authDomain: 'starsimapp.firebaseapp.com',
    storageBucket: 'starsimapp.firebasestorage.app',
    measurementId: 'G-0WC8XJ27XT',
  );

}